disabled_rules: # rule identifiers to exclude from running
  - todo
opt_in_rules: # some rules are only opt-in
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - duplicate_imports
  - empty_count
  - empty_parentheses_with_trailing_closure
  - force_unwrapping
  - for_where
  - mark
#  - missing_docs
  - overridden_super_call
  - private_over_fileprivate
  - redundant_type_annotation
  - strict_fileprivate
#  - strong_iboutlet - 2/27/2020 - team decided to revert this for now
  - unneeded_parentheses_in_closure_argument
  # Find all the available rules by running:
  # swiftlint rules
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 120 # warning
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 500 # error
# or they can set both explicitly
file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true
function_parameter_count:
  warning: 6
  error: 8
cyclomatic_complexity:
  warning: 15
  error: 25
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
  - iPhone # excluded via string
  - ID
  - No
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - !str on
    - URL
    - x
    - y
reporter: "xcode"
